---
- hosts: [TTO]
  vars:
    ansible_user: "{{ TTO_USER }}"
    ansible_ssh_private_key_file: "{{ TTO_KEY_FILE }}"
    USER_NAME: "{{ TTO_USER }}"
  tasks:
    - name : "run TickToOrder test"
      shell: " ./run.sh restart; ./py_trigger.py "
      args:
        warn: no
        chdir: "/home/{{ USER_NAME }}/strategy/TickToOrder"
    - name : "get TickToOrder test LOG to ./tmp/"
      fetch:
        src: "/home/{{ USER_NAME }}/strategy/TickToOrder/StrategyCenter.LOG"
        dest: "tmp/TTO-{{ inventory_hostname }}-{{ ansible_date_time.iso8601_basic_short }}.LOG"
        flat: yes
...

