---
- name: "set full multiuser mode"
  become: yes
  become_user: root
  lineinfile:
    dest: /etc/inittab
    regexp: "^id"
    line: "id:3:initdefault:"

- name: "Setup alternate SSH port"
  become: yes
  become_user: root
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "^Port"
    line: "Port 3022"
  notify: "Restart sshd"

- name: "Disable empty password login"
  become: yes
  become_user: root
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "^#?PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"
  notify: "Restart sshd"

- name: Disable password login
  become: yes
  become_user: root
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: "Restart sshd"

- name: Enable PAM
  become: yes
  become_user: root
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "^#?UsePAM"
    line: "UsePAM yes"
  notify: "Restart sshd"

  #  - name: Disable remote root login
  #    become: yes
  #    become_user: root
  #    lineinfile: dest={{ sshd_config }} regexp="^#?PermitRootLogin" line="PermitRootLogin no"
  #    notify: "Restart sshd"

